[build]
  publish = "build" 
  command = "npm run build" 

[dev]
  framework = "react"
  targetPort = 3000
  port = 8888

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
